name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [4.10.0, 4.9.0]
        dist: ["alpine", "debian", "ubuntu"]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_REGISTRY_USER }}
          password: ${{ secrets.TENCENT_REGISTRY_PASSWORD }}
      - name: Build
        run: make build CV=${{ matrix.version }} DIST=${{ matrix.dist }}
      - name: Test
        run: make test CV=${{ matrix.version }} DIST=${{ matrix.dist }}
      - name: Push
        run: make push CV=${{ matrix.version }} DIST=${{ matrix.dist }}

  latest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_REGISTRY_USER }}
          password: ${{ secrets.TENCENT_REGISTRY_PASSWORD }}
      - name: Latest
        run: make latest CV=4.10.0 DIST=fedora
